services:
  academycheckinapi-pg:
    image: bitnami/postgresql
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: academycheckinapidb
    ports:
      - "5432:5432"
