services:
  academycheckinapi-pg:
    image: bitnami/postgresql
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: academycheckinapidb
    ports:
      - "5432:5432"
